services:
  mysql:
    image: mysql:8.0
    container_name: springboot-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: usersdb
    ports:
      - "3306:3306"
    volumes:
      - springboot-mysql-data:/var/lib/mysql

volumes:
  springboot-mysql-data:
